export const domainDataTypes = [
  { value: 'string', label: 'String' },
  { value: 'number', label: 'Number' },
  { value: 'integer', label: 'Integer' },
  { value: 'boolean', label: 'Boolean' },
  { value: 'date', label: 'Date' },
  { value: 'datetime', label: 'DateTime' },
  { value: 'time', label: 'Time' },
  { value: 'uuid', label: 'UUID' },
  { value: 'json', label: 'JSON' },
  { value: 'text', label: 'Text' },
  { value: 'decimal', label: 'Decimal' },
  { value: 'float', label: 'Float' },
  { value: 'double', label: 'Double' },
  { value: 'blob', label: 'Blob' },
  { value: 'enum', label: 'Enum' },
]; 